AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Sandbox for messing around

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: !Ref RootDomainName
      WebsiteConfiguration:
        IndexDocument: "index.html"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: "*"
            Sid: "PublicReadGetObject"